openapi: 3.0.3
info:
  title: Products API - OpenAPI 3.0
  version: 1.0.0
servers:
  - url: https://e93bk9ngf2.execute-api.us-east-1.amazonaws.com/prod/
paths:
  /products:
    get:
      tags:
        - products
      summary: Get List of all products
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /product/{productId}:
    get:
      tags:
        - products
      summary: Find product by ID
      description: Returns a single product
      parameters:
        - name: productId
          in: path
          description: ID of product to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
components:
  schemas:
    Product:
      required:
        - description
        - price
        - title
      type: object
      properties:
        id:
          type: string
          example: 7567ec4b-b10c-48c5-9345-fc73c48a80aa
        title:
          type: string
          example: ProductOne
        description:
          type: string
          example: ProductOne Description
        price:
          type: number
          example: 15
      xml:
        name: product